In [2]:
import numpy as n

In [11]:
arr = n.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [14]:
a = [1,2,3.5,4,5]
a

[1, 2, 3.5, 4, 5]

In [15]:
n.array(a)


array([1. , 2. , 3.5, 4. , 5. ])

In [17]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
n.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr = n.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
arr = n.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
arr = n.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

random generation function*

In [42]:
n.random.rand(10)

array([0.04956763, 0.51521088, 0.60854801, 0.35680295, 0.09817844,
       0.26140448, 0.24831305, 0.35720065, 0.00462108, 0.30149465])

In [49]:
n.random.randn(10)

array([-0.8487066 , -1.72763679, -1.20107589, -0.12352534,  2.05309105,
        0.49216   , -0.49719632, -0.52408389, -0.27376669,  0.36603923])

In [58]:
np.random.randint(10,20,5)

array([11, 10, 13, 18, 14], dtype=int32)

In [78]:
arr = n.array([[1,2,3],[4,4,4],[5,5,5],[6,6,20]])
arr

array([[ 1,  2,  3],
       [ 4,  4,  4],
       [ 5,  5,  5],
       [ 6,  6, 20]])

In [68]:
arr.shape

(4, 3)

In [69]:
arr.size

12

In [71]:
arr.dtype

dtype('int64')

array method

In [77]:
arr

array([[1, 2, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [73]:
arr.min()

np.int64(1)

In [74]:
arr.max()

np.int64(6)

In [79]:
arr.sum()

np.int64(65)

In [82]:
n.sum(arr,axis = 0)


array([16, 17, 32])

In [83]:
n.sum(arr,axis = 1)

array([ 6, 12, 15, 32])

In [84]:
arr.mean()

np.float64(5.416666666666667)

In [85]:
arr.std()

np.float64(4.627064103967246)

In [89]:
arr.argmax()

np.int64(11)

In [99]:
arr1 =  n.arange(1,31)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [100]:
arr = arr1.reshape(6,5)

In [101]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])